# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] =  'yes'

Vagrant.configure(2) do |config|

    NodeCount = 1

    (1..NodeCount).each do |i|
        config.vm.define "k8svm#{i}" do |node|
            node.vm.box = "ubuntu/bionic64"
            node.disksize.size = "20GB"
            node.vm.hostname = "k8svm#{i}.example.com"
            node.vm.netwwork "private_network", ip: "172.42.42.10#{i}"
            node.vm.provider "virtualbox" do |v|
                v.name = "k8svm#{i}"
                v.memory = 4096
                v.cpus = 2
            end
        end
    end
end